# -*- coding: utf-8 -*-
"""AI Diet & Nutrition Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O9uc4hV0jKGYHr2Mr9bOa4uctgPVej-O

# 🥗 AI Diet & Nutrition Analyzer
### Interactive App — Powered by Groq (Free API)

## Step 1: Install & Setup
"""

!pip install groq pillow matplotlib pandas numpy ipywidgets --quiet
from IPython.display import display, HTML, clear_output
import ipywidgets as widgets
print("✅ Done! If widgets do not show, go to: Runtime → Restart Session → Run All")

"""## Step 2: Enter Your Groq API Key
> Get free key at 👉 https://console.groq.com (no credit card needed)
"""

from groq import Groq
import json, re, io, base64
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import PIL.Image
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output
import warnings
warnings.filterwarnings('ignore')

# ── Paste your Groq API key here ──────────────────────
GROQ_API_KEY = "add your groq key"  # <-- replace
# ──────────────────────────────────────────────────────

client = Groq(api_key=GROQ_API_KEY)
MODEL  = "llama-3.3-70b-versatile"

def ask(prompt, system="You are an expert nutritionist.", max_tokens=1500):
    r = client.chat.completions.create(
        model=MODEL,
        messages=[{"role":"system","content":system},{"role":"user","content":prompt}],
        max_tokens=max_tokens, temperature=0.3
    )
    return r.choices[0].message.content.strip()

def extract_json(text):
    text = re.sub(r'```(?:json)?','',text).strip('`').strip()
    try: return json.loads(text)
    except:
        m = re.search(r'\{.*\}', text, re.DOTALL)
        if m:
            try: return json.loads(m.group())
            except: pass
    return None

try:
    ask("Say: ready", max_tokens=5)
    print("✅ Groq API connected! Scroll down to launch the app ⬇️")
except Exception as e:
    print(f"❌ {e}")

"""## Step 3: Launch the App ▶️"""

# ═══════════════════════════════════════════════════════════
#   CSS STYLES
# ═══════════════════════════════════════════════════════════
APP_CSS = """
<style>
  .app-container { font-family: 'Segoe UI', sans-serif; max-width: 860px; margin: 0 auto; }
  .app-header {
    background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
    color: white; padding: 28px 32px; border-radius: 16px; margin-bottom: 20px;
    box-shadow: 0 8px 32px rgba(0,0,0,0.3);
  }
  .app-header h1 { margin:0; font-size:28px; font-weight:700; }
  .app-header p  { margin:6px 0 0; opacity:0.75; font-size:14px; }
  .tab-bar {
    display:flex; gap:8px; margin-bottom:20px; flex-wrap:wrap;
  }
  .tab-btn {
    padding:10px 20px; border:none; border-radius:10px; cursor:pointer;
    font-size:14px; font-weight:600; transition:all 0.2s;
    background:#f0f4ff; color:#4a5568;
  }
  .tab-btn.active { background:linear-gradient(135deg,#667eea,#764ba2); color:white; box-shadow:0 4px 12px rgba(102,126,234,0.4); }
  .card {
    background:white; border-radius:14px; padding:24px;
    box-shadow:0 2px 16px rgba(0,0,0,0.08); margin-bottom:16px;
    border:1px solid #f0f0f0;
  }
  .card h3 { margin:0 0 16px; color:#2d3748; font-size:17px; }
  .input-group { margin-bottom:14px; }
  .input-group label { display:block; font-size:13px; font-weight:600; color:#4a5568; margin-bottom:5px; }
  .input-row { display:grid; grid-template-columns:1fr 1fr; gap:14px; }
  .input-row3 { display:grid; grid-template-columns:1fr 1fr 1fr; gap:14px; }
  .run-btn {
    width:100%; padding:14px; border:none; border-radius:12px; cursor:pointer;
    font-size:16px; font-weight:700; color:white; margin-top:8px;
    background:linear-gradient(135deg,#667eea,#764ba2);
    box-shadow:0 4px 16px rgba(102,126,234,0.4);
    transition:transform 0.15s, box-shadow 0.15s;
  }
  .run-btn:hover { transform:translateY(-2px); box-shadow:0 6px 20px rgba(102,126,234,0.5); }
  .result-card {
    background:white; border-radius:14px; padding:24px;
    box-shadow:0 2px 16px rgba(0,0,0,0.08); margin-top:16px;
    border-left:5px solid #667eea;
  }
  .stat-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:12px; margin:16px 0; }
  .stat-box {
    background:#f8f9ff; border-radius:10px; padding:14px; text-align:center;
    border:1px solid #e8ecff;
  }
  .stat-box .val { font-size:24px; font-weight:800; color:#667eea; }
  .stat-box .lbl { font-size:12px; color:#666; margin-top:2px; }
  .badge {
    display:inline-block; padding:3px 10px; border-radius:20px; font-size:12px;
    font-weight:600; margin:2px;
  }
  .badge-green  { background:#e6f9f0; color:#1a7a4a; }
  .badge-red    { background:#fff0f0; color:#c0392b; }
  .badge-orange { background:#fff8e6; color:#b7791f; }
  .badge-blue   { background:#e8f0ff; color:#2c5282; }
  .rec-item {
    display:flex; align-items:flex-start; gap:10px; padding:10px 14px;
    border-radius:10px; margin-bottom:8px; background:#f8f9ff;
    border-left:3px solid #667eea;
  }
  .micro-row { display:flex; justify-content:space-between; align-items:center;
    padding:8px 12px; border-radius:8px; margin-bottom:6px; background:#f8f9ff; }
  .progress-bar { height:8px; border-radius:4px; background:#e2e8f0; overflow:hidden; margin-top:6px; }
  .progress-fill { height:100%; border-radius:4px; background:linear-gradient(90deg,#667eea,#764ba2); }
  .meal-card {
    background:#f8f9ff; border-radius:10px; padding:14px; margin-bottom:10px;
    border-left:4px solid #667eea;
  }
  .chat-bubble { padding:12px 16px; border-radius:12px; margin-bottom:10px; line-height:1.6; }
  .chat-user { background:#667eea; color:white; margin-left:40px; border-radius:12px 12px 4px 12px; }
  .chat-ai   { background:#f0f4ff; color:#2d3748; margin-right:40px; border-radius:12px 12px 12px 4px; }
  .score-circle {
    width:120px; height:120px; border-radius:50%; margin:0 auto 16px;
    display:flex; flex-direction:column; align-items:center; justify-content:center;
    font-weight:800; box-shadow:0 4px 20px rgba(102,126,234,0.3);
    background:linear-gradient(135deg,#667eea,#764ba2); color:white;
  }
  .score-circle .score-num { font-size:32px; line-height:1; }
  .score-circle .score-lbl { font-size:11px; opacity:0.85; }
  textarea { width:100%; padding:10px; border:1.5px solid #e2e8f0; border-radius:10px;
    font-family:inherit; font-size:14px; resize:vertical; box-sizing:border-box; outline:none; }
  textarea:focus { border-color:#667eea; }
  select, input[type=text], input[type=number] {
    width:100%; padding:9px 12px; border:1.5px solid #e2e8f0; border-radius:10px;
    font-size:14px; font-family:inherit; box-sizing:border-box; outline:none; background:white;
  }
  select:focus, input:focus { border-color:#667eea; }
  .spinner { text-align:center; padding:40px; color:#667eea; font-size:16px; }
  hr { border:none; border-top:1px solid #f0f0f0; margin:20px 0; }
</style>
"""

# ═══════════════════════════════════════════════════════════
#   ANALYSIS FUNCTIONS
# ═══════════════════════════════════════════════════════════

def analyze_food(food_name, quantity):
    prompt = f"""Nutritional info for: {food_name}, serving: {quantity}
Return ONLY valid JSON:
{{"food_name":"{food_name}","serving_size":"{quantity}","calories":250,
"macros":{{"protein_g":10,"carbs_g":35,"fat_g":8,"fiber_g":3,"sugar_g":5}},
"minerals":{{"calcium_mg":50,"iron_mg":2,"potassium_mg":300,"sodium_mg":200}},
"vitamins":{{"vitamin_c_mg":10,"vitamin_d_iu":0,"folate_mcg":20}},
"glycemic_index":55,"glycemic_load":12,"inflammation_score":"Neutral",
"antioxidant_rich":true,
"health_benefits":["Benefit 1","Benefit 2"],
"health_concerns":["Concern if any"],
"cooking_tips":"Best prep method",
"fun_fact":"Interesting fact"}}"""
    return extract_json(ask(prompt))

def full_assessment(meals, profile):
    meals_text = "\n".join([f"- {k}: {v}" for k,v in meals.items()])
    prompt = f"""Diet assessment. Return ONLY valid JSON:
Profile: Age {profile['age']}, {profile['gender']}, {profile['weight']}kg, {profile['height']}cm,
Activity: {profile['activity']}, Goal: {profile['goal']}, Diet: {profile['diet']}, Conditions: {profile['conditions']}
Meals: {meals_text}
{{"bmr_calories":1800,"tdee_calories":2200,"target_calories":1900,"total_calories_consumed":1750,
"calorie_status":"Under Target",
"macros":{{"protein_g":{{"consumed":80,"target":90,"status":"Low"}},"carbs_g":{{"consumed":220,"target":240,"status":"Good"}},"fat_g":{{"consumed":55,"target":60,"status":"Good"}},"fiber_g":{{"consumed":18,"target":25,"status":"Low"}},"water_ml":{{"consumed":1500,"target":2500,"status":"Low"}}}},
"micronutrient_analysis":[{{"nutrient":"Iron","status":"Deficient","food_sources":["spinach","lentils"]}},{{"nutrient":"Vitamin D","status":"Low","food_sources":["eggs"]}},{{"nutrient":"Calcium","status":"Adequate","food_sources":[]}}],
"diet_quality_score":72,"diet_quality_grade":"B",
"strengths":["Good variety","Adequate protein"],
"deficiencies":["Low fiber","Low iron"],
"health_risks":["Constipation risk"],
"recommendations":[{{"priority":"High","action":"Drink 2 more glasses of water"}},{{"priority":"Medium","action":"Add leafy greens for iron"}}],
"meal_suggestions":{{"breakfast":"Oats with fruits","lunch":"Brown rice with dal","dinner":"Chapati with paneer","snacks":"Fruits and nuts"}},
"foods_to_increase":["Lentils","Leafy greens","Nuts"],
"foods_to_avoid":["Processed snacks","Sugary drinks"],
"supplements_suggested":["Vitamin D3","Iron"],
"weekly_plan_tip":"Add one extra vegetable serving per meal.",
"overall_assessment":"Your diet is moderate. Focus on fiber and hydration."}}"""
    return extract_json(ask(prompt, max_tokens=2000))

def generate_plan(profile, prefs):
    prompt = f"""Create 7-day Indian meal plan.
Profile: Age {profile['age']}, {profile['gender']}, {profile['weight']}kg, {profile['height']}cm,
Activity: {profile['activity']}, Goal: {profile['goal']}, Diet: {profile['diet']}, Preferences: {prefs}
Show each day: Breakfast/Mid-Morning/Lunch/Snack/Dinner with calories.
End with 5 practical tips. Make it detailed and practical."""
    return ask(prompt, max_tokens=2500)

def chat_response(question, history, profile_ctx):
    system = ("You are Dr. Nutri, a friendly expert AI dietitian specialising in South Asian diets. "
              "Give practical, science-backed advice. Use emojis. Be warm and clear.")
    hist_text = "\n".join([f"User: {h['q']}\nDr.Nutri: {h['a']}" for h in history[-3:]])
    prompt = f"Context: {profile_ctx}\n\nConversation:\n{hist_text}\n\nUser: {question}"
    return ask(prompt, system=system, max_tokens=600)


# ═══════════════════════════════════════════════════════════
#   CHART HELPERS  (render to base64 PNG for HTML embed)
# ═══════════════════════════════════════════════════════════

def fig_to_b64(fig):
    buf = io.BytesIO()
    fig.savefig(buf, format='png', bbox_inches='tight', dpi=110, facecolor='white')
    buf.seek(0)
    b64 = base64.b64encode(buf.read()).decode()
    plt.close(fig)
    return f'<img src="data:image/png;base64,{b64}" style="max-width:100%;border-radius:10px;margin-top:10px;">'

def macro_pie_html(macros, title=""):
    labels,sizes,colors = [],[],[]
    cmap = {'protein':('#4CAF50','Protein'),'carb':('#2196F3','Carbs'),
            'fat':('#FF9800','Fat'),'fiber':('#9C27B0','Fiber'),'sugar':('#F44336','Sugar')}
    for key,val in macros.items():
        if isinstance(val,dict): val=val.get('consumed',0)
        clean=key.lower().replace('_g','')
        for k,(c,lbl) in cmap.items():
            if k in clean and float(val or 0)>0:
                sizes.append(float(val)); labels.append(f"{lbl}\n{val}g"); colors.append(c); break
    if not sizes: return ""
    fig,ax=plt.subplots(figsize=(5,4))
    ax.pie(sizes,labels=labels,colors=colors,autopct='%1.0f%%',startangle=90,
           wedgeprops=dict(width=0.55,edgecolor='white',linewidth=2))
    ax.text(0,0,f'{sum(sizes):.0f}g\nTotal',ha='center',va='center',fontsize=10,fontweight='bold')
    if title: ax.set_title(title,fontsize=11,fontweight='bold')
    return fig_to_b64(fig)

def bar_chart_html(macros):
    nutrients,consumed_vals,target_vals=[],[],[]
    for k,v in macros.items():
        if isinstance(v,dict):
            consumed_vals.append(float(v.get('consumed',0)))
            target_vals.append(float(v.get('target',1)))
            nutrients.append(k.replace('_g','').replace('_ml','').replace('_',' ').title())
    if not nutrients: return ""
    x=np.arange(len(nutrients)); w=0.35
    bar_colors=['#4CAF50' if c<=t else '#F44336' for c,t in zip(consumed_vals,target_vals)]
    fig,ax=plt.subplots(figsize=(8,4))
    ax.bar(x-w/2,consumed_vals,w,label='Consumed',color=bar_colors,alpha=0.85,edgecolor='white')
    ax.bar(x+w/2,target_vals,  w,label='Target',  color='#90A4AE',alpha=0.6, edgecolor='white')
    ax.set_xticks(x); ax.set_xticklabels(nutrients,rotation=20,ha='right',fontsize=10)
    ax.legend(fontsize=10); ax.grid(axis='y',alpha=0.3); ax.set_ylabel('Amount')
    ax.set_title('Macronutrients: Consumed vs Target',fontsize=12,fontweight='bold')
    fig.patch.set_facecolor('white')
    return fig_to_b64(fig)


# ═══════════════════════════════════════════════════════════
#   HTML RESULT BUILDERS
# ═══════════════════════════════════════════════════════════

def build_food_result(data):
    if not data: return "<p>Could not parse response.</p>"
    macros = data.get('macros',{})
    pie = macro_pie_html(macros, "Macronutrient Split")
    benefits = "".join([f'<span class="badge badge-green">✅ {b}</span>' for b in data.get('health_benefits',[])])
    concerns  = "".join([f'<span class="badge badge-red">⚠️ {c}</span>'  for c in data.get('health_concerns',[])])
    macro_rows = "".join([
        f'<div class="micro-row"><span><b>{k.replace("_g","").replace("_"," ").title()}</b></span>'
        f'<span style="color:#667eea;font-weight:700">{v}g</span></div>'
        for k,v in macros.items()
    ])
    return f"""
<div class="result-card">
  <h3>🍽️ {data.get('food_name','')} <small style="color:#888;font-weight:400">— {data.get('serving_size','')}</small></h3>
  <div class="stat-grid">
    <div class="stat-box"><div class="val">{data.get('calories','—')}</div><div class="lbl">Calories (kcal)</div></div>
    <div class="stat-box"><div class="val">{data.get('glycemic_index','—')}</div><div class="lbl">Glycemic Index</div></div>
    <div class="stat-box"><div class="val">{'Yes' if data.get('antioxidant_rich') else 'No'}</div><div class="lbl">Antioxidant Rich</div></div>
  </div>
  <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;">
    <div><h4 style="margin:0 0 8px;color:#4a5568">📊 Macronutrients</h4>{macro_rows}</div>
    <div>{pie}</div>
  </div>
  <hr>
  <div><h4 style="margin:0 0 8px;color:#4a5568">Health</h4>{benefits}{concerns}</div>
  <hr>
  <p style="margin:0;color:#555;font-size:14px">💡 <b>Tip:</b> {data.get('cooking_tips','')}</p>
  <p style="margin:8px 0 0;color:#555;font-size:13px">🎯 <b>Fun fact:</b> {data.get('fun_fact','')}</p>
</div>"""

def build_assessment_result(data, profile):
    if not data: return "<p>Could not parse response.</p>"
    score = data.get('diet_quality_score',0)
    grade = data.get('diet_quality_grade','')
    status = data.get('calorie_status','')
    status_color = '#27ae60' if 'Target' in status else ('#e67e22' if 'Under' in status else '#e74c3c')
    macros = data.get('macros',{})
    bar = bar_chart_html(macros)
    pie = macro_pie_html({k:v.get('consumed',0) if isinstance(v,dict) else v for k,v in macros.items()})

    micro_rows = ""
    for m in data.get('micronutrient_analysis',[]):
        color = '#27ae60' if m['status']=='Adequate' else ('#e67e22' if m['status']=='Low' else '#e74c3c')
        icon  = '✅' if m['status']=='Adequate' else ('⚠️' if m['status']=='Low' else '❌')
        src   = ', '.join(m.get('food_sources',[])[:3]) or '—'
        micro_rows += f'<div class="micro-row"><span>{icon} <b>{m["nutrient"]}</b></span><span style="color:{color};font-weight:600">{m["status"]}</span><span style="color:#888;font-size:12px">{src}</span></div>'

    recs = ""
    for r in data.get('recommendations',[]):
        p=r.get('priority',''); icon='🔴' if p=='High' else('🟡' if p=='Medium' else '🟢')
        recs += f'<div class="rec-item">{icon} <div><b>{p} Priority</b><br><span style="font-size:13px;color:#555">{r.get("action","")}</span></div></div>'

    strengths  = "".join([f'<span class="badge badge-green">✅ {s}</span>' for s in data.get('strengths',[])])
    deficits   = "".join([f'<span class="badge badge-red">❌ {d}</span>'   for d in data.get('deficiencies',[])])
    risks      = "".join([f'<span class="badge badge-orange">⚠️ {r}</span>' for r in data.get('health_risks',[])])
    increase   = "".join([f'<span class="badge badge-green">🥬 {f}</span>'  for f in data.get('foods_to_increase',[])])
    avoid      = "".join([f'<span class="badge badge-red">🚫 {f}</span>'    for f in data.get('foods_to_avoid',[])])
    supps      = "".join([f'<span class="badge badge-blue">💊 {s}</span>'   for s in data.get('supplements_suggested',[])])

    sug = data.get('meal_suggestions',{})
    meal_cards = "".join([f'<div class="meal-card"><b>{k.title()}</b><br><span style="color:#555;font-size:13px">{v}</span></div>' for k,v in sug.items()])

    return f"""
<div class="result-card">
  <h3>📋 Dietary Assessment — {profile.get('age')}yr {profile.get('gender')}</h3>
  <div class="stat-grid">
    <div class="stat-box"><div class="val">{data.get('total_calories_consumed','—')}</div><div class="lbl">Calories Consumed</div></div>
    <div class="stat-box"><div class="val">{data.get('target_calories','—')}</div><div class="lbl">Daily Target</div></div>
    <div class="stat-box"><div class="val" style="color:{status_color}">{status}</div><div class="lbl">Calorie Status</div></div>
  </div>

  <div style="text-align:center;margin:20px 0">
    <div class="score-circle">
      <div class="score-num">{score}</div>
      <div class="score-lbl">/ 100 · Grade {grade}</div>
    </div>
    <div style="color:#555;font-size:14px">Diet Quality Score</div>
  </div>

  <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:16px">
    <div>{bar}</div><div>{pie}</div>
  </div>

  <h4 style="margin:0 0 8px;color:#4a5568">🧬 Micronutrients</h4>
  {micro_rows}
  <hr>
  <h4 style="margin:0 0 8px;color:#4a5568">💪 Strengths</h4>{strengths}
  <h4 style="margin:12px 0 8px;color:#4a5568">⚠️ Deficiencies</h4>{deficits}
  <h4 style="margin:12px 0 8px;color:#4a5568">🏥 Risks</h4>{risks}
  <hr>
  <h4 style="margin:0 0 8px;color:#4a5568">💡 Recommendations</h4>{recs}
  <hr>
  <h4 style="margin:0 0 8px;color:#4a5568">🍽️ Healthier Meal Suggestions</h4>{meal_cards}
  <hr>
  <div>
    <h4 style="margin:0 0 8px;color:#4a5568">Foods & Supplements</h4>
    <div>{increase}</div>
    <div style="margin-top:6px">{avoid}</div>
    <div style="margin-top:6px">{supps}</div>
  </div>
  <hr>
  <p style="color:#555;font-size:14px;margin:0">📝 <b>Overall:</b> {data.get('overall_assessment','')}</p>
  <p style="color:#667eea;font-size:14px;margin:8px 0 0">🗓️ <b>This Week:</b> {data.get('weekly_plan_tip','')}</p>
</div>"""


# ═══════════════════════════════════════════════════════════
#   APP STATE
# ═══════════════════════════════════════════════════════════
app_state = {
    "tab": "food",
    "chat_history": [],
    "chat_profile_ctx": ""
}

# ─── Output areas ───
out_food       = widgets.Output()
out_assess     = widgets.Output()
out_plan       = widgets.Output()
out_chat_msgs  = widgets.Output()

# ═══════════════════════════════════════════════════════════
#   TAB 1 — FOOD ANALYZER
# ═══════════════════════════════════════════════════════════
food_input = widgets.Text(placeholder="e.g. Chicken Biryani, Idli, Apple",
    layout=widgets.Layout(width='100%', height='40px'))
food_qty   = widgets.Text(value="1 serving (200g)",
    layout=widgets.Layout(width='100%', height='40px'))
food_btn   = widgets.Button(description="🔍 Analyze Food",
    layout=widgets.Layout(width='100%', height='44px'),
    style=widgets.ButtonStyle(button_color='#667eea', font_weight='bold', font_size='15px'))

def on_food_analyze(b):
    with out_food:
        clear_output()
        display(HTML('<div class="spinner">🔍 Analyzing food... please wait</div>'))
    food_name = food_input.value.strip() or "Banana"
    qty       = food_qty.value.strip()   or "100g"
    data = analyze_food(food_name, qty)
    with out_food:
        clear_output()
        display(HTML(APP_CSS + '<div class="app-container">' + build_food_result(data) + '</div>'))

food_btn.on_click(on_food_analyze)

# ═══════════════════════════════════════════════════════════
#   TAB 2 — DIET ASSESSMENT
# ═══════════════════════════════════════════════════════════
age_w    = widgets.Text(value="28",       placeholder="Age")
weight_w = widgets.Text(value="70",       placeholder="Weight kg")
height_w = widgets.Text(value="170",      placeholder="Height cm")
gender_w = widgets.Dropdown(options=["Male","Female","Other"], value="Male",
               layout=widgets.Layout(width='100%'))
activity_w = widgets.Dropdown(
    options=["Sedentary","Lightly Active","Moderately Active","Very Active"],
    value="Moderately Active", layout=widgets.Layout(width='100%'))
goal_w = widgets.Dropdown(
    options=["Lose Weight","Gain Muscle","Maintain Weight","Improve Health"],
    value="Lose Weight", layout=widgets.Layout(width='100%'))
diet_w = widgets.Dropdown(
    options=["No Restriction","Vegetarian","Vegan","Keto","Paleo","Diabetic-Friendly"],
    value="Vegetarian", layout=widgets.Layout(width='100%'))
conditions_w = widgets.Text(value="None", placeholder="e.g. Diabetes, None")

breakfast_w = widgets.Textarea(value="2 idli with sambar and coconut chutney, 1 cup tea",
    placeholder="Breakfast...", layout=widgets.Layout(width='100%', height='60px'))
lunch_w     = widgets.Textarea(value="2 chapati, dal tadka, sabzi, small bowl rice",
    placeholder="Lunch...", layout=widgets.Layout(width='100%', height='60px'))
dinner_w    = widgets.Textarea(value="2 chapati, paneer butter masala, salad",
    placeholder="Dinner...", layout=widgets.Layout(width='100%', height='60px'))
snacks_w    = widgets.Textarea(value="1 banana, 10 almonds, chai with biscuits",
    placeholder="Snacks...", layout=widgets.Layout(width='100%', height='60px'))
water_w     = widgets.Text(value="6 glasses", placeholder="Water intake")

assess_btn = widgets.Button(description="📋 Run Assessment",
    layout=widgets.Layout(width='100%', height='44px'),
    style=widgets.ButtonStyle(button_color='#764ba2', font_weight='bold', font_size='15px'))

def on_assess(b):
    with out_assess:
        clear_output()
        display(HTML('<div class="spinner">📋 Analyzing your diet... please wait</div>'))
    profile = {
        "age": age_w.value, "gender": gender_w.value,
        "weight": weight_w.value, "height": height_w.value,
        "activity": activity_w.value, "goal": goal_w.value,
        "diet": diet_w.value, "conditions": conditions_w.value
    }
    meals = {"Breakfast": breakfast_w.value, "Lunch": lunch_w.value,
             "Dinner": dinner_w.value, "Snacks": snacks_w.value,
             "Water": water_w.value}
    app_state["chat_profile_ctx"] = f"{profile['age']}yr {profile['gender']}, {profile['weight']}kg, goal:{profile['goal']}, diet:{profile['diet']}"
    data = full_assessment(meals, profile)
    with out_assess:
        clear_output()
        display(HTML(APP_CSS + '<div class="app-container">' + build_assessment_result(data, profile) + '</div>'))

assess_btn.on_click(on_assess)

# ═══════════════════════════════════════════════════════════
#   TAB 3 — MEAL PLAN
# ═══════════════════════════════════════════════════════════
plan_age_w    = widgets.Text(value="28", layout=widgets.Layout(width='100%'))
plan_weight_w = widgets.Text(value="70", layout=widgets.Layout(width='100%'))
plan_height_w = widgets.Text(value="170",layout=widgets.Layout(width='100%'))
plan_gender_w = widgets.Dropdown(options=["Male","Female","Other"],value="Male",layout=widgets.Layout(width='100%'))
plan_activity_w=widgets.Dropdown(options=["Sedentary","Lightly Active","Moderately Active","Very Active"],
    value="Moderately Active",layout=widgets.Layout(width='100%'))
plan_goal_w   = widgets.Dropdown(options=["Lose Weight","Gain Muscle","Maintain Weight"],
    value="Lose Weight",layout=widgets.Layout(width='100%'))
plan_diet_w   = widgets.Dropdown(options=["No Restriction","Vegetarian","Vegan","Keto"],
    value="Vegetarian",layout=widgets.Layout(width='100%'))
plan_prefs_w  = widgets.Textarea(value="I like Gujarati food, no onion-garlic",
    layout=widgets.Layout(width='100%', height='70px'))
plan_btn = widgets.Button(description="📅 Generate 7-Day Plan",
    layout=widgets.Layout(width='100%', height='44px'),
    style=widgets.ButtonStyle(button_color='#27ae60', font_weight='bold', font_size='15px'))

def on_plan(b):
    with out_plan:
        clear_output()
        display(HTML('<div class="spinner">📅 Creating your personalized meal plan... please wait</div>'))
    profile = {"age":plan_age_w.value,"gender":plan_gender_w.value,"weight":plan_weight_w.value,
               "height":plan_height_w.value,"activity":plan_activity_w.value,
               "goal":plan_goal_w.value,"diet":plan_diet_w.value}
    result = generate_plan(profile, plan_prefs_w.value)
    formatted = result.replace("\n","<br>").replace("Day ","<br><b>🗓️ Day ")
    with out_plan:
        clear_output()
        display(HTML(APP_CSS + f'<div class="app-container"><div class="result-card"><h3>📅 Your 7-Day Meal Plan</h3><div style="line-height:1.8;color:#2d3748;font-size:14px">{formatted}</div></div></div>'))

plan_btn.on_click(on_plan)

# ═══════════════════════════════════════════════════════════
#   TAB 4 — CHATBOT
# ═══════════════════════════════════════════════════════════
chat_input = widgets.Text(placeholder="Ask Dr. Nutri anything about diet & nutrition...",
    layout=widgets.Layout(width='100%', height='40px'))
chat_send  = widgets.Button(description="Send ➤",
    layout=widgets.Layout(width='130px', height='40px'),
    style=widgets.ButtonStyle(button_color='#667eea', font_weight='bold'))
chat_clear = widgets.Button(description="🗑️ Clear",
    layout=widgets.Layout(width='100px', height='40px'),
    style=widgets.ButtonStyle(button_color='#e74c3c', font_weight='bold'))

def render_chat():
    with out_chat_msgs:
        clear_output()
        if not app_state["chat_history"]:
            display(HTML('<div style="text-align:center;padding:30px;color:#888">👋 Hi! I am Dr. Nutri. Ask me anything about diet and nutrition!</div>'))
            return
        bubbles = ""
        for h in app_state["chat_history"]:
            bubbles += f'<div class="chat-bubble chat-user">🧑 {h["q"]}</div>'
            bubbles += f'<div class="chat-bubble chat-ai">🥗 <b>Dr. Nutri:</b><br>{h["a"].replace(chr(10),"<br>")}</div>'
        display(HTML(APP_CSS + f'<div class="app-container">{bubbles}</div>'))

def on_chat_send(b):
    q = chat_input.value.strip()
    if not q: return
    chat_input.value = ""
    with out_chat_msgs:
        clear_output()
        display(HTML('<div class="spinner">💬 Dr. Nutri is thinking...</div>'))
    ans = chat_response(q, app_state["chat_history"], app_state["chat_profile_ctx"])
    app_state["chat_history"].append({"q":q,"a":ans})
    render_chat()

def on_chat_clear(b):
    app_state["chat_history"] = []
    render_chat()

chat_send.on_click(on_chat_send)
chat_clear.on_click(on_chat_clear)

# ═══════════════════════════════════════════════════════════
#   LAYOUT BUILDER
# ═══════════════════════════════════════════════════════════
W  = widgets.Layout(width='100%')
lbl = lambda t: widgets.HTML(f'<label style="font-size:13px;font-weight:600;color:#4a5568;display:block;margin-bottom:4px">{t}</label>')

tab1 = widgets.VBox([
    widgets.HTML('<div class="card"><h3>🔍 Food Analyzer</h3><p style="color:#888;font-size:13px;margin:0 0 16px">Get complete nutritional breakdown of any food item</p></div>'),
    widgets.HTML(APP_CSS),
    lbl("Food Name"), food_input,
    lbl("Quantity / Serving Size"), food_qty,
    food_btn, out_food
], layout=W)

tab2 = widgets.VBox([
    widgets.HTML('<div class="card"><h3>📋 Daily Diet Assessment</h3><p style="color:#888;font-size:13px;margin:0 0 16px">Log your meals and get a comprehensive nutritional analysis</p></div>'),
    widgets.HTML("<b style='color:#4a5568'>👤 Your Profile</b>"),
    widgets.HBox([widgets.VBox([lbl("Age"),age_w],layout=widgets.Layout(width='25%')),
                  widgets.VBox([lbl("Weight (kg)"),weight_w],layout=widgets.Layout(width='25%')),
                  widgets.VBox([lbl("Height (cm)"),height_w],layout=widgets.Layout(width='25%')),
                  widgets.VBox([lbl("Gender"),gender_w],layout=widgets.Layout(width='25%'))]),
    widgets.HBox([widgets.VBox([lbl("Activity Level"),activity_w],layout=widgets.Layout(width='33%')),
                  widgets.VBox([lbl("Health Goal"),goal_w],layout=widgets.Layout(width='33%')),
                  widgets.VBox([lbl("Diet Type"),diet_w],layout=widgets.Layout(width='34%'))]),
    lbl("Medical Conditions"), conditions_w,
    widgets.HTML("<br><b style='color:#4a5568'>🍽️ Today's Meals</b>"),
    lbl("Breakfast"), breakfast_w,
    lbl("Lunch"), lunch_w,
    lbl("Dinner"), dinner_w,
    lbl("Snacks"), snacks_w,
    lbl("Water Intake"), water_w,
    assess_btn, out_assess
], layout=W)

tab3 = widgets.VBox([
    widgets.HTML('<div class="card"><h3>📅 7-Day Meal Plan Generator</h3><p style="color:#888;font-size:13px;margin:0 0 16px">Get a personalized weekly Indian meal plan</p></div>'),
    widgets.HBox([widgets.VBox([lbl("Age"),plan_age_w],layout=widgets.Layout(width='25%')),
                  widgets.VBox([lbl("Weight (kg)"),plan_weight_w],layout=widgets.Layout(width='25%')),
                  widgets.VBox([lbl("Height (cm)"),plan_height_w],layout=widgets.Layout(width='25%')),
                  widgets.VBox([lbl("Gender"),plan_gender_w],layout=widgets.Layout(width='25%'))]),
    widgets.HBox([widgets.VBox([lbl("Activity"),plan_activity_w],layout=widgets.Layout(width='33%')),
                  widgets.VBox([lbl("Goal"),plan_goal_w],layout=widgets.Layout(width='33%')),
                  widgets.VBox([lbl("Diet"),plan_diet_w],layout=widgets.Layout(width='34%'))]),
    lbl("Preferences / Restrictions"), plan_prefs_w,
    plan_btn, out_plan
], layout=W)

tab4 = widgets.VBox([
    widgets.HTML('<div class="card"><h3>🤖 Dr. Nutri — AI Diet Chatbot</h3><p style="color:#888;font-size:13px;margin:0 0 4px">Ask anything about nutrition, diet, and healthy eating</p></div>'),
    out_chat_msgs,
    widgets.HBox([chat_input, chat_send, chat_clear], layout=W),
], layout=W)

# ═══════════════════════════════════════════════════════════
#   RENDER APP
# ═══════════════════════════════════════════════════════════
tab_widget = widgets.Tab(children=[tab1, tab2, tab3, tab4])
tab_widget.set_title(0, "🔍 Food Analyzer")
tab_widget.set_title(1, "📋 Diet Assessment")
tab_widget.set_title(2, "📅 Meal Planner")
tab_widget.set_title(3, "🤖 Dr.Nutri chat")
tab_widget.layout = widgets.Layout(width='100%', min_height='500px')

header = widgets.HTML(APP_CSS + """
<div class="app-header">
  <h1>🥗 AI Diet & Nutrition Analyzer</h1>
  <p>Powered by Groq LLaMA 3.3 · Free API · Personalized for Indian diets</p>
</div>
""")

render_chat()
display(widgets.VBox([header, tab_widget]))